name: CI Pipeline

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checar código do repositório
        uses: actions/checkout@v2

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v1

      - name: Build da imagem Docker
        run: docker build -t python-ci-cd .

      - name: Rodar testes no Docker
        run: docker run --rm python-ci-cd
